[build]
  command = "yarn build && yarn build:lambda"
  functions= "service/lambda"
  publish = "build"

[context.production.environment]
    REACT_APP_STAGE="production"

[context.staging.environment]
    REACT_APP_STAGE="staging"